Feature/user welcome
barabas007/first_api pull request #1
Opened 2021-05-03 17:11 UTC by barabas007

Сделал авторизацию пользователя.....посмотри плиз.

2021-05-03 17:14 UTC, amveng commented on .idea/railways.cache
>          rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
подобных файлов в репо быть не должно , надо настраивать гитигнор

2021-05-03 17:22 UTC, amveng commented on app/controllers/application_controller.rb
> +    User.find_by(id: session[:user_id])
где взять сессию то ? как бы она только в браузере куков в апи не передается

2021-05-03 17:38 UTC, amveng commented on app/controllers/application_controller.rb
> +class ApplicationController < ActionController::API::Base
как это ваще может работать ? поидее недолжно

2021-05-03 17:38 UTC, amveng commented on config/routes.rb
> +
роуты неверные см условия задачи

2021-05-03 17:39 UTC, amveng reviewed
доработать по условиям задачи

2021-05-04 06:07 UTC, alxekb requested changes

2021-05-04 06:07 UTC, alxekb commented on .idea/dataSources.xml
> +</project>
@barabas007 Please add a new line here 🙂

2021-05-04 06:07 UTC, alxekb commented on app/controllers/application_controller.rb
> +class ApplicationController < ActionController::API::Base
@barabas007 [ActionController::Base](https://api.rubyonrails.org/classes/ActionController/Base.html) please double check this guide.

2021-05-04 06:07 UTC, alxekb commented on app/controllers/application_controller.rb
> +    User.find_by(id: session[:user_id])
Are we handling a Null scenario here? @barabas007

2021-05-04 06:07 UTC, alxekb commented on app/controllers/application_controller.rb
> +    !current_user.nil?
@barabas007 I'm not sure here. 😉

2021-05-04 06:07 UTC, alxekb commented on app/controllers/application_controller.rb
> +    redirect_to '/welcome' unless logged_in?
@barabas007 I can't understand why we have this redirect. Is it an API based controller?

2021-05-04 06:07 UTC, alxekb commented on app/controllers/users_controller.rb
> +    @usrer = User.new
@barabas007 it's a typo here IMO 🙂

2021-05-04 06:07 UTC, alxekb commented on app/controllers/users_controller.rb
>      render json: User.all
@barabas007 👀

2021-05-04 06:07 UTC, alxekb commented on app/controllers/users_controller.rb
> +    @user = User.create(params.require(:user).permit(:username, :password))
@barabas007 Please refactor this.

2021-05-04 06:07 UTC, alxekb commented on app/models/welcome.rb
> +end
@barabas007 🙂

2021-05-04 06:07 UTC, alxekb commented on db/migrate/20210503164737_create_welcomes.rb
> +end
😿  @barabas007

2021-05-04 06:07 UTC, alxekb commented on test/controllers/sessions_controller_test.rb
> +
@barabas007 Please consider to use RSpec instead of minitest.

2021-05-04 06:07 UTC, alxekb commented on test/models/welcome_test.rb
> +  # end
@barabas007 Please remove this.

2021-05-04 06:07 UTC, alxekb commented on test/fixtures/welcomes.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
@barabas007 👀

2021-06-05 08:45 UTC, barabas007 commented
bla bla

2021-06-05 08:46 UTC, barabas007 commented
111

2021-06-05 08:47 UTC, closed without merging